name: dms_datastore
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - beautifulsoup4
  - dask
  - numba
  - scipy
  - tqdm
  - openpyxl
  - boto3 # for hrrr 
  - lxml # for pandas html parsing
  - paramiko # for sftp cimis requests
  - tabula-py>=2.9.0 # for pdf parsing
  - jpype1
  - numpy
  - pandas>=2
  - cfgrib
  - xarray
  - vtools3
  - pyyaml
  - gdal
  - pytz # a new hrrr dependency ?
  - pyshp # a new schimpy dependency ?
  - schimpy # remove this!
  - eccodes
  - seaborn
  - matplotlib
  - scikit-learn
  - contourpy
  - joblib
  - fonttools
  - pyparsing
  - kiwisolver
  - diskcache
  - httpx
  - pytest
  - pytest-runner
#- pip:
  #   - -e git+https://github.com/CADWRDeltaModeling/dms_datastore#egg=dms_datastore
# alternatively if you want to develop ...
# git clone this repo
# conda env create -f environment.yml
# pip install --no-deps -e . 
