name: dms_datastore
channels:
  - cadwr-dms
  - conda-forge
#  - nodefaults # removing so that tabula-py can be installed from main as conda-forge version is too old
dependencies:
  - python=3.12
  - pip
  - beautifulsoup4
  - dask
  - numba
  - scipy
  - tqdm
  - openpyxl
  - boto3 # for hrrr 
  - lxml # for pandas html parsing
  - paramiko # for sftp cimis requests
  - tabula-py>=2.9.0 # for pdf parsing
  - jpype1
  - numpy
  - pandas>=2
  - cfgrib
  - xarray
  - vtools3
  - pyyaml
  - gdal
  - pytz # a new hrrr dependency ?
  - pyshp # a new schimpy dependency ?
  - schimpy # remove this!
  - eccodes
  - bokeh
  - hvplot
  - panel
  - seaborn
  - matplotlib
  - scikit-learn
  - contourpy
  - joblib
  - fonttools
  - pyparsing
  - kiwisolver
  - diskcache
  - dms-datastore