name: dms_datastore
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - beautifulsoup4
  - dask
  - numba
  - scipy
  - tqdm
  - openpyxl
  - boto3 # for hrrr 
  - lxml # for pandas html parsing
  - paramiko # for sftp cimis requests
  - numpy
  - pandas>=2
  - cfgrib
  - pyarrow
  - xarray
  - vtools3
  - pyyaml
  - gdal
  - pytz # a new hrrr dependency ?
  - pyshp # a new schimpy dependency ?
  - libgdal
  - rasterstats
  - schimpy # remove this!
  - eccodes
  - bokeh
  - hvplot
  - panel
  - seaborn
  - matplotlib
  - scikit-learn
  - contourpy
  - joblib
  - fonttools
  - pyparsing
  - kiwisolver
  - diskcache
  - dms-datastore
  - pip:
    - tabula-py>=2.9.0  # installed via pip to avoid conda channel conflicts (conda-forge is outdated)
    - jpype1