


station_dbase : station_dbase.csv
variable_mappings: variable_mappings.csv
variable_definitions: variables.csv
sublocations: station_subloc.csv

file_deletion_list: non_15_min_files_checked.txt
compare_excepts_formatted: compare_excepts_formatted.txt

des_time_partition: des_rationalize_cfg.yaml


repo: "//cnrastore-bdo/Modeling_Data/repo/continuous/screened"
screened: "//cnrastore-bdo/Modeling_Data/repo/continuous/screened"
processed: "//cnrastore-bdo/Modeling_Data/repo/continuous/processed"

source_priority:
  ncro: ['ncro','cdec']
  dwr_ncro: ['ncro']
  des: ['des']
  dwr_des: ['des']
  usgs: ['usgs']
  noaa: ['noaa']
  usbr: ['usbr','cdec']
  dwr_om: ['cdec']
  dwr: ['dwr','cdec']
  ebmud: ['usgs','ebmud','cdec']
  
screen_config_v20230126: screen_config_v20230126.yaml
screen_config: screen_config_v20230126.yaml
